plugins:
 - jekyll-seo-tag
 - jekyll-multiple-languages-plugin
 - jekyll-sitemap

title: Teatro Vecchio
short_title: Teatro
description: >
  Your description
github_username: your_github_username
twitter_username: your_twitter_username
external_links: [['http://venezia86.it', 'venezia86.it']]
languages: ["en", "it"]
baseurl: ""
permalink: /:title/
url: "http://your-url.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - "*.gemspec"
  - LICENSE.txt
  - README.md
  - Dockerfile
  - docker-compose.yml

exclude_from_localizations:
  - javascript
  - images
  - css
  - robots.txt
  - sitemap_index.xml
  - manifest.json

header_pages:
  - about.md
