plugins:
 - jekyll-seo-tag

title: Teatro Vecchio
description: >
  Your description
github_username: your_github_username
twitter_username: your_twitter_username
external_links: [['http://venezia86.it', 'venezia86.it']]
# google_analytics_account: UA-GOOGLE-ANALITYCS-ID
